---
- name: Levantar Node Exporter con Docker
  community.docker.docker_container:
    name: node_exporter
    image: prom/node-exporter:v1.8.2
    state: started
    restart_policy: unless-stopped
    network_mode: host
    pid_mode: host
    volumes:
      - /:/host:ro,rslave
    command:
      - '--path.rootfs=/host'
