---
- name: Recargar systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Aplicar desactivación de offloads en NIC de captura
  ansible.builtin.systemd:
    name: suricata-nic-offloads.service
    state: restarted

- name: Reiniciar contenedor de Suricata
  community.docker.docker_container:
    name: "{{ suricata_container_name }}"
    state: started
    restart: true
